### ISSUE TITLE
Sidebar vertical scroll issue

### ISSUE THREAD

**Issue by julianriise** [nodalit/agiliate-engine-client#1]
## Issue description
- Unable to view the full input sidebar
- Bottom part is cut off when scrolling all the way down
- Browsers tested: *Arc Browser*, *Google Chrome*
- Link used: https://linkarkitektur.github.io/agiliate-engine-client/

## Illustration
<img width="690" alt="screenshot-of-agiliate-client" src="https://github.com/linkarkitektur/agiliate-engine-client/assets/77626314/e2ad50e3-7532-4a1e-a313-8683cff49789">

**Comment by huulbaek** [comment]
Thank you, fixed in https://github.com/linkarkitektur/agiliate-engine-client/commit/25f2953e72395290e9d81fe7a933b5382a14e680
